name: ethernative
favicon: null
layout_spectrum: 0.44051840738393366
typography_spectrum: 0.6012264518067241
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.06144359824247658
  lightness: 0.7124781371094286
  saturation: 0.860452474327758
  rhythmicContrast: 0.0756952001247555
purpose: []
